//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeEditor.WPF.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThemeEditor.WPF.Localization.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading BGM....
        /// </summary>
        public static string Busy_LoadingBGM {
            get {
                return ResourceManager.GetString("Busy_LoadingBGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Theme....
        /// </summary>
        public static string Busy_LoadingTheme {
            get {
                return ResourceManager.GetString("Busy_LoadingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Image....
        /// </summary>
        public static string Busy_OpeningImage {
            get {
                return ResourceManager.GetString("Busy_OpeningImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking File.
        /// </summary>
        public static string Busy_PickingFile {
            get {
                return ResourceManager.GetString("Busy_PickingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Image....
        /// </summary>
        public static string Busy_SavingImage {
            get {
                return ResourceManager.GetString("Busy_SavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Theme....
        /// </summary>
        public static string Busy_SavingTheme {
            get {
                return ResourceManager.GetString("Busy_SavingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabilishing Connection....
        /// </summary>
        public static string Busy_Sender_Connecting {
            get {
                return ResourceManager.GetString("Busy_Sender_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string Busy_Sender_ConnectionError {
            get {
                return ResourceManager.GetString("Busy_Sender_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Theme....
        /// </summary>
        public static string Busy_Sender_SendingTheme {
            get {
                return ResourceManager.GetString("Busy_Sender_SendingTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM.
        /// </summary>
        public static string Control_AudioPlayer_Label {
            get {
                return ResourceManager.GetString("Control_AudioPlayer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Control_AudioPlayer_Pause {
            get {
                return ResourceManager.GetString("Control_AudioPlayer_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Control_AudioPlayer_Play {
            get {
                return ResourceManager.GetString("Control_AudioPlayer_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Control_AudioPlayer_Reload {
            get {
                return ResourceManager.GetString("Control_AudioPlayer_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Control_AudioPlayer_Stop {
            get {
                return ResourceManager.GetString("Control_AudioPlayer_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Control_ColorPicker_Advanced {
            get {
                return ResourceManager.GetString("Control_ColorPicker_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Image Palette.
        /// </summary>
        public static string Control_ColorPicker_BottomPalette {
            get {
                return ResourceManager.GetString("Control_ColorPicker_BottomPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Colors.
        /// </summary>
        public static string Control_ColorPicker_Recent {
            get {
                return ResourceManager.GetString("Control_ColorPicker_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        public static string Control_ColorPicker_Standard {
            get {
                return ResourceManager.GetString("Control_ColorPicker_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Image Palette.
        /// </summary>
        public static string Control_ColorPicker_TopPalette {
            get {
                return ResourceManager.GetString("Control_ColorPicker_TopPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        public static string Control_Preview_Animate {
            get {
                return ResourceManager.GetString("Control_Preview_Animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Close&quot;.
        /// </summary>
        public static string Control_Preview_CloseButton {
            get {
                return ResourceManager.GetString("Control_Preview_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Control_Preview_Folder {
            get {
                return ResourceManager.GetString("Control_Preview_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Control_Preview_Label {
            get {
                return ResourceManager.GetString("Control_Preview_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Control_Preview_Options {
            get {
                return ResourceManager.GetString("Control_Preview_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressed.
        /// </summary>
        public static string Control_Preview_Pressed {
            get {
                return ResourceManager.GetString("Control_Preview_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Control_Toggle_False {
            get {
                return ResourceManager.GetString("Control_Toggle_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Control_Toggle_True {
            get {
                return ResourceManager.GetString("Control_Toggle_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Preview.
        /// </summary>
        public static string Menu_File_SavePreview {
            get {
                return ResourceManager.GetString("Menu_File_SavePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Menu_File_SavePreview_Both {
            get {
                return ResourceManager.GetString("Menu_File_SavePreview_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Menu_File_SavePreview_Bottom {
            get {
                return ResourceManager.GetString("Menu_File_SavePreview_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Menu_File_SavePreview_Top {
            get {
                return ResourceManager.GetString("Menu_File_SavePreview_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Image.
        /// </summary>
        public static string Menu_Image {
            get {
                return ResourceManager.GetString("Menu_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        public static string Menu_Image_Any_Export {
            get {
                return ResourceManager.GetString("Menu_Image_Any_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string Menu_Image_Any_Load {
            get {
                return ResourceManager.GetString("Menu_Image_Any_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Menu_Image_Any_Remove {
            get {
                return ResourceManager.GetString("Menu_Image_Any_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bottom.
        /// </summary>
        public static string Menu_Image_Bottom {
            get {
                return ResourceManager.GetString("Menu_Image_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File (_Large).
        /// </summary>
        public static string Menu_Image_FileLarge {
            get {
                return ResourceManager.GetString("Menu_Image_FileLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File (_Small).
        /// </summary>
        public static string Menu_Image_FileSmall {
            get {
                return ResourceManager.GetString("Menu_Image_FileSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder (_Closed).
        /// </summary>
        public static string Menu_Image_FolderClosed {
            get {
                return ResourceManager.GetString("Menu_Image_FolderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder (_Open).
        /// </summary>
        public static string Menu_Image_FolderOpen {
            get {
                return ResourceManager.GetString("Menu_Image_FolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Icon (SMDH).
        /// </summary>
        public static string Menu_Image_LargeIcon {
            get {
                return ResourceManager.GetString("Menu_Image_LargeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Icon (SMDH).
        /// </summary>
        public static string Menu_Image_SmallIcon {
            get {
                return ResourceManager.GetString("Menu_Image_SmallIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Top.
        /// </summary>
        public static string Menu_Image_Top {
            get {
                return ResourceManager.GetString("Menu_Image_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (_Alternative).
        /// </summary>
        public static string Menu_Image_TopStatic {
            get {
                return ResourceManager.GetString("Menu_Image_TopStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Menu_Metadata {
            get {
                return ResourceManager.GetString("Menu_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Colors.
        /// </summary>
        public static string Menu_Metadata_ExportColors {
            get {
                return ResourceManager.GetString("Menu_Metadata_ExportColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Flags.
        /// </summary>
        public static string Menu_Metadata_ExportFlags {
            get {
                return ResourceManager.GetString("Menu_Metadata_ExportFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Menu_Metadata_Import {
            get {
                return ResourceManager.GetString("Menu_Metadata_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To.
        /// </summary>
        public static string Menu_SendTo {
            get {
                return ResourceManager.GetString("Menu_SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Background Music Flag was Enabled:
        /// - Make sure the BGM.BCSTM file is present on your device when before the Theme, otherwise it&apos;ll crash!.
        /// </summary>
        public static string Message_BackgroundMusicLoaded {
            get {
                return ResourceManager.GetString("Message_BackgroundMusicLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image Size.
        /// </summary>
        public static string Message_InvalidImageSize {
            get {
                return ResourceManager.GetString("Message_InvalidImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Sizes.
        /// </summary>
        public static string Message_InvalidImageSize_AllowedSizes {
            get {
                return ResourceManager.GetString("Message_InvalidImageSize_AllowedSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Background Music Flag was Disabled:
        /// - Background Music Flag is Checked, however no BGM.BCSTM File was found.
        /// - Place the BGM.BCSTM file alongside the Theme, then press the &quot;Reload BGM&quot; Button to enable it again..
        /// </summary>
        public static string Message_NoBackgroundMusicOnLoad {
            get {
                return ResourceManager.GetString("Message_NoBackgroundMusicOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Background Music Flag is Set:
        /// - No BGM.BCSTM file is present on the saved path
        /// - Make sure the BGM.BCSTM file is present on your device before applying the Theme, otherwise it&apos;ll crash!.
        /// </summary>
        public static string Message_NoBackgroundMusicOnSave {
            get {
                return ResourceManager.GetString("Message_NoBackgroundMusicOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Saved.
        /// </summary>
        public static string Message_PreviewSaved {
            get {
                return ResourceManager.GetString("Message_PreviewSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Saved Successfully.
        /// </summary>
        public static string Message_ThemeSaved {
            get {
                return ResourceManager.GetString("Message_ThemeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Sent Successfully.
        /// </summary>
        public static string Message_ThemeSent {
            get {
                return ResourceManager.GetString("Message_ThemeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Updated Version is Available:
        ///Check the About Window for more Information.
        /// </summary>
        public static string Message_UpdateAvailable {
            get {
                return ResourceManager.GetString("Message_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M/dd (ddd).
        /// </summary>
        public static string Preview_DateFormat {
            get {
                return ResourceManager.GetString("Preview_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH.
        /// </summary>
        public static string Preview_HourFormat {
            get {
                return ResourceManager.GetString("Preview_HourFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Preview_MinFormat {
            get {
                return ResourceManager.GetString("Preview_MinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Preview_Options_Cart {
            get {
                return ResourceManager.GetString("Preview_Options_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Preview_Options_Column {
            get {
                return ResourceManager.GetString("Preview_Options_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor.
        /// </summary>
        public static string Preview_Options_Cursor {
            get {
                return ResourceManager.GetString("Preview_Options_Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Preview_Options_File {
            get {
                return ResourceManager.GetString("Preview_Options_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Preview_Options_Folder {
            get {
                return ResourceManager.GetString("Preview_Options_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Preview.
        /// </summary>
        public static string Preview_Options_FolderMode {
            get {
                return ResourceManager.GetString("Preview_Options_FolderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Preview.
        /// </summary>
        public static string Preview_Options_MainMode {
            get {
                return ResourceManager.GetString("Preview_Options_MainMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Preview_Options_Row {
            get {
                return ResourceManager.GetString("Preview_Options_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Tab_Colors {
            get {
                return ResourceManager.GetString("Tab_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Tab_Flags {
            get {
                return ResourceManager.GetString("Tab_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Info.
        /// </summary>
        public static string Tab_Info {
            get {
                return ResourceManager.GetString("Tab_Info", resourceCulture);
            }
        }
    }
}
