//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeEditor.WPF.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThemeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThemeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThemeEditor.WPF.Localization.ThemeResources", typeof(ThemeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_DrawType_None {
            get {
                return ResourceManager.GetString("Enum_DrawType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Color.
        /// </summary>
        public static string Enum_DrawType_SolidColor {
            get {
                return ResourceManager.GetString("Enum_DrawType_SolidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Color &amp; Texture.
        /// </summary>
        public static string Enum_DrawType_SolidColorTexture {
            get {
                return ResourceManager.GetString("Enum_DrawType_SolidColorTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture.
        /// </summary>
        public static string Enum_DrawType_Texture {
            get {
                return ResourceManager.GetString("Enum_DrawType_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounce Scroll (1-2-3-2-1).
        /// </summary>
        public static string Enum_FrameType_BounceScroll {
            get {
                return ResourceManager.GetString("Enum_FrameType_BounceScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Scroll.
        /// </summary>
        public static string Enum_FrameType_FastScroll {
            get {
                return ResourceManager.GetString("Enum_FrameType_FastScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Scroll (1-2-3-1-2-3).
        /// </summary>
        public static string Enum_FrameType_PageScroll {
            get {
                return ResourceManager.GetString("Enum_FrameType_PageScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Enum_FrameType_Single {
            get {
                return ResourceManager.GetString("Enum_FrameType_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Scroll.
        /// </summary>
        public static string Enum_FrameType_SlowScroll {
            get {
                return ResourceManager.GetString("Enum_FrameType_SlowScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enum_GameText_Color {
            get {
                return ResourceManager.GetString("Enum_GameText_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Enum_GameText_Hidden {
            get {
                return ResourceManager.GetString("Enum_GameText_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Enum_GameText_None {
            get {
                return ResourceManager.GetString("Enum_GameText_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        public static string Theme_Colors_Arrow {
            get {
                return ResourceManager.GetString("Theme_Colors_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Button.
        /// </summary>
        public static string Theme_Colors_Arrow_Button {
            get {
                return ResourceManager.GetString("Theme_Colors_Arrow_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging Button with the Arrow.
        /// </summary>
        public static string Theme_Colors_Arrow_Button_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Arrow_Button_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string Theme_Colors_Arrow_Button_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Arrow_Button_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow in the Paging Button.
        /// </summary>
        public static string Theme_Colors_Arrow_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Arrow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string Theme_Colors_Arrow_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Arrow_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Background Inner.
        /// </summary>
        public static string Theme_Colors_Bottom_Background_Inner {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Background_Inner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Screen Background Inner Area.
        /// </summary>
        public static string Theme_Colors_Bottom_Background_Inner_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Background_Inner_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Theme_Colors_Bottom_Background_Inner_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Background_Inner_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Background Outer.
        /// </summary>
        public static string Theme_Colors_Bottom_Background_Outer {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Background_Outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Screen Background Outer Area..
        /// </summary>
        public static string Theme_Colors_Bottom_Background_Outer_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Background_Outer_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Theme_Colors_Bottom_Background_Outer_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Background_Outer_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Corner Buttons.
        /// </summary>
        public static string Theme_Colors_Bottom_Corner {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Screen Settings and Resize Buttons.
        /// </summary>
        public static string Theme_Colors_Bottom_Corner_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Corner_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Theme_Colors_Bottom_Corner_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Bottom_Corner_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Button.
        /// </summary>
        public static string Theme_Colors_Close {
            get {
                return ResourceManager.GetString("Theme_Colors_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Software Button.
        /// </summary>
        public static string Theme_Colors_Close_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Close_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Theme_Colors_Close_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Close_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor.
        /// </summary>
        public static string Theme_Colors_Cursor {
            get {
                return ResourceManager.GetString("Theme_Colors_Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Screen Selection Cursor.
        /// </summary>
        public static string Theme_Colors_Cursor_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Cursor_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Theme_Colors_Cursor_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Cursor_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Text.
        /// </summary>
        public static string Theme_Colors_Demo_Text {
            get {
                return ResourceManager.GetString("Theme_Colors_Demo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Software Demo Launches.
        /// </summary>
        public static string Theme_Colors_Demo_Text_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Demo_Text_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string Theme_Colors_Demo_Text_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Demo_Text_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D File.
        /// </summary>
        public static string Theme_Colors_File {
            get {
                return ResourceManager.GetString("Theme_Colors_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Titles Icon.
        /// </summary>
        public static string Theme_Colors_File_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_File_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Theme_Colors_File_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_File_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Folder.
        /// </summary>
        public static string Theme_Colors_Folder {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Back Arrow.
        /// </summary>
        public static string Theme_Colors_Folder_Arrow {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Arrow Button on Folder View.
        /// </summary>
        public static string Theme_Colors_Folder_Arrow_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder_Arrow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string Theme_Colors_Folder_Arrow_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder_Arrow_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Background.
        /// </summary>
        public static string Theme_Colors_Folder_Background {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Screen Inner Area when on Folder View.
        /// </summary>
        public static string Theme_Colors_Folder_Background_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder_Background_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string Theme_Colors_Folder_Background_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder_Background_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Folder Icon.
        /// </summary>
        public static string Theme_Colors_Folder_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string Theme_Colors_Folder_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Folder_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Text.
        /// </summary>
        public static string Theme_Colors_Game_Text {
            get {
                return ResourceManager.GetString("Theme_Colors_Game_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Description when on a Single Row Layout.
        /// </summary>
        public static string Theme_Colors_Game_Text_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Game_Text_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string Theme_Colors_Game_Text_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Game_Text_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Button.
        /// </summary>
        public static string Theme_Colors_Open {
            get {
                return ResourceManager.GetString("Theme_Colors_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Software/Create Folder Button.
        /// </summary>
        public static string Theme_Colors_Open_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Open_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Theme_Colors_Open_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Open_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Background.
        /// </summary>
        public static string Theme_Colors_Top_Background {
            get {
                return ResourceManager.GetString("Theme_Colors_Top_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Screen Background Colors.
        /// </summary>
        public static string Theme_Colors_Top_Background_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Top_Background_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Theme_Colors_Top_Background_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Top_Background_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Corner Buttons.
        /// </summary>
        public static string Theme_Colors_Top_Corner {
            get {
                return ResourceManager.GetString("Theme_Colors_Top_Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Screen Screenshot and Camera Buttons.
        /// </summary>
        public static string Theme_Colors_Top_Corner_Desc {
            get {
                return ResourceManager.GetString("Theme_Colors_Top_Corner_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Theme_Colors_Top_Corner_Order {
            get {
                return ResourceManager.GetString("Theme_Colors_Top_Corner_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Button Color.
        /// </summary>
        public static string Theme_Flags_Arrow_Button_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Arrow_Button_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Paging Button Custom Colors.
        /// </summary>
        public static string Theme_Flags_Arrow_Button_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Arrow_Button_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        public static string Theme_Flags_Arrow_Button_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Arrow_Button_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Color.
        /// </summary>
        public static string Theme_Flags_Arrow_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Arrow_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Paging Button Arrow Custom Colors.
        /// </summary>
        public static string Theme_Flags_Arrow_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Arrow_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string Theme_Flags_Arrow_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Arrow_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Music.
        /// </summary>
        public static string Theme_Flags_Background_Music {
            get {
                return ResourceManager.GetString("Theme_Flags_Background_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Background Music (BGM.BCSTM).
        /// </summary>
        public static string Theme_Flags_Background_Music_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Background_Music_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string Theme_Flags_Background_Music_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Background_Music_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Background Inner Color.
        /// </summary>
        public static string Theme_Flags_Bottom_Background_Inner_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Background_Inner_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Bottom Screen Background Inner Area Custom Colors.
        /// </summary>
        public static string Theme_Flags_Bottom_Background_Inner_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Background_Inner_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Theme_Flags_Bottom_Background_Inner_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Background_Inner_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Background Outer Color.
        /// </summary>
        public static string Theme_Flags_Bottom_Background_Outer_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Background_Outer_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Bottom Screen Background Outer Area Custom Colors.
        /// </summary>
        public static string Theme_Flags_Bottom_Background_Outer_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Background_Outer_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string Theme_Flags_Bottom_Background_Outer_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Background_Outer_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Corner Buttons Color.
        /// </summary>
        public static string Theme_Flags_Bottom_Corner_Button_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Corner_Button_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Settings and Resize Button Custom Colors.
        /// </summary>
        public static string Theme_Flags_Bottom_Corner_Button_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Corner_Button_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string Theme_Flags_Bottom_Corner_Button_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Corner_Button_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Screen Draw Type.
        /// </summary>
        public static string Theme_Flags_Bottom_Draw_Type {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Draw_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects Bottom Screen Render Mode.
        /// </summary>
        public static string Theme_Flags_Bottom_Draw_Type_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Draw_Type_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Theme_Flags_Bottom_Draw_Type_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Draw_Type_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Screen Frame Type.
        /// </summary>
        public static string Theme_Flags_Bottom_Frame_Type {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Frame_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects Bottom Screen Frame Type.
        /// </summary>
        public static string Theme_Flags_Bottom_Frame_Type_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Frame_Type_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Theme_Flags_Bottom_Frame_Type_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Bottom_Frame_Type_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor Colors.
        /// </summary>
        public static string Theme_Flags_Cursor_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Cursor_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Cursor Custom Colors.
        /// </summary>
        public static string Theme_Flags_Cursor_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Cursor_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string Theme_Flags_Cursor_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Cursor_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Text Color.
        /// </summary>
        public static string Theme_Flags_Demo_Text_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Demo_Text_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Demo Test Custom Color.
        /// </summary>
        public static string Theme_Flags_Demo_Text_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Demo_Text_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string Theme_Flags_Demo_Text_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Demo_Text_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D File Color.
        /// </summary>
        public static string Theme_Flags_File_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_File_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables 3D File Custom Color.
        /// </summary>
        public static string Theme_Flags_File_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_File_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string Theme_Flags_File_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_File_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Texture.
        /// </summary>
        public static string Theme_Flags_File_Texture {
            get {
                return ResourceManager.GetString("Theme_Flags_File_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables File Icon Custom Texture.
        /// </summary>
        public static string Theme_Flags_File_Texture_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_File_Texture_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string Theme_Flags_File_Texture_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_File_Texture_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Arrow Color.
        /// </summary>
        public static string Theme_Flags_Folder_Arrow_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Arrow_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Folder View Back Arrow Custom Colors.
        /// </summary>
        public static string Theme_Flags_Folder_Arrow_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Arrow_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string Theme_Flags_Folder_Arrow_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Arrow_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Background Color.
        /// </summary>
        public static string Theme_Flags_Folder_Background_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Background_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Folder View Background Custom Colors.
        /// </summary>
        public static string Theme_Flags_Folder_Background_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Background_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string Theme_Flags_Folder_Background_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Background_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Folder Color.
        /// </summary>
        public static string Theme_Flags_Folder_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables 3D Folder Custom Colors.
        /// </summary>
        public static string Theme_Flags_Folder_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Theme_Flags_Folder_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Texture.
        /// </summary>
        public static string Theme_Flags_Folder_Texture {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Folder Icon Custom Texture.
        /// </summary>
        public static string Theme_Flags_Folder_Texture_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Texture_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string Theme_Flags_Folder_Texture_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Folder_Texture_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Text Color.
        /// </summary>
        public static string Theme_Flags_Game_Text_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Game_Text_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Game Text Custom Colors.
        /// </summary>
        public static string Theme_Flags_Game_Text_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Game_Text_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string Theme_Flags_Game_Text_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Game_Text_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open / Close Colors.
        /// </summary>
        public static string Theme_Flags_Open_Close_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Open_Close_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Open/Close Software Button Custom Colors.
        /// </summary>
        public static string Theme_Flags_Open_Close_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Open_Close_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Theme_Flags_Open_Close_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Open_Close_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Effects.
        /// </summary>
        public static string Theme_Flags_Sound_Effect {
            get {
                return ResourceManager.GetString("Theme_Flags_Sound_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Sound Effect (CWAV Data).
        /// </summary>
        public static string Theme_Flags_Sound_Effect_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Sound_Effect_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string Theme_Flags_Sound_Effect_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Sound_Effect_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Background Color.
        /// </summary>
        public static string Theme_Flags_Top_Background_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Background_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Top Screen Background Custom Colors.
        /// </summary>
        public static string Theme_Flags_Top_Background_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Background_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Theme_Flags_Top_Background_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Background_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Corner Button Color.
        /// </summary>
        public static string Theme_Flags_Top_Corner_Button_Color {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Corner_Button_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Top Screen Camera Buttons Custom Colors.
        /// </summary>
        public static string Theme_Flags_Top_Corner_Button_Color_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Corner_Button_Color_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Theme_Flags_Top_Corner_Button_Color_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Corner_Button_Color_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Screen Draw Type.
        /// </summary>
        public static string Theme_Flags_Top_Draw_Type {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Draw_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects Top Screen Render Mode.
        /// </summary>
        public static string Theme_Flags_Top_Draw_Type_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Draw_Type_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Theme_Flags_Top_Draw_Type_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Draw_Type_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Screen Frame Type.
        /// </summary>
        public static string Theme_Flags_Top_Frame_Type {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Frame_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects Top Screen Frame Type.
        /// </summary>
        public static string Theme_Flags_Top_Frame_Type_Desc {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Frame_Type_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Theme_Flags_Top_Frame_Type_Order {
            get {
                return ResourceManager.GetString("Theme_Flags_Top_Frame_Type_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Theme_Info_Author {
            get {
                return ResourceManager.GetString("Theme_Info_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Author.
        /// </summary>
        public static string Theme_Info_Author_Desc {
            get {
                return ResourceManager.GetString("Theme_Info_Author_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Icon.
        /// </summary>
        public static string Theme_Info_LargeIcon {
            get {
                return ResourceManager.GetString("Theme_Info_LargeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48px Icon.
        /// </summary>
        public static string Theme_Info_LargeIcon_Desc {
            get {
                return ResourceManager.GetString("Theme_Info_LargeIcon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Description.
        /// </summary>
        public static string Theme_Info_LongDesc {
            get {
                return ResourceManager.GetString("Theme_Info_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Description.
        /// </summary>
        public static string Theme_Info_LongDesc_Desc {
            get {
                return ResourceManager.GetString("Theme_Info_LongDesc_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string Theme_Info_ShortDesc {
            get {
                return ResourceManager.GetString("Theme_Info_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string Theme_Info_ShortDesc_Desc {
            get {
                return ResourceManager.GetString("Theme_Info_ShortDesc_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Icon.
        /// </summary>
        public static string Theme_Info_SmallIcon {
            get {
                return ResourceManager.GetString("Theme_Info_SmallIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24px Icon.
        /// </summary>
        public static string Theme_Info_SmallIcon_Desc {
            get {
                return ResourceManager.GetString("Theme_Info_SmallIcon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string Theme_Sets_Arrow_Border {
            get {
                return ResourceManager.GetString("Theme_Sets_Arrow_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Color.
        /// </summary>
        public static string Theme_Sets_Arrow_Border_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Arrow_Border_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressed.
        /// </summary>
        public static string Theme_Sets_Arrow_Pressed {
            get {
                return ResourceManager.GetString("Theme_Sets_Arrow_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressed Color.
        /// </summary>
        public static string Theme_Sets_Arrow_Pressed_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Arrow_Pressed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpressed.
        /// </summary>
        public static string Theme_Sets_Arrow_Unpressed {
            get {
                return ResourceManager.GetString("Theme_Sets_Arrow_Unpressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpressed Color.
        /// </summary>
        public static string Theme_Sets_Arrow_Unpressed_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Arrow_Unpressed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        public static string Theme_Sets_ArrowButton_Glow {
            get {
                return ResourceManager.GetString("Theme_Sets_ArrowButton_Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow Color.
        /// </summary>
        public static string Theme_Sets_ArrowButton_Glow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_ArrowButton_Glow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_ArrowButton_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_ArrowButton_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_ArrowButton_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_ArrowButton_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading.
        /// </summary>
        public static string Theme_Sets_ArrowButton_Shading {
            get {
                return ResourceManager.GetString("Theme_Sets_ArrowButton_Shading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading Color.
        /// </summary>
        public static string Theme_Sets_ArrowButton_Shading_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_ArrowButton_Shading_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string Theme_Sets_BottomCorner_Border {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Color.
        /// </summary>
        public static string Theme_Sets_BottomCorner_Border_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_Border_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Theme_Sets_BottomCorner_Highlight {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Color.
        /// </summary>
        public static string Theme_Sets_BottomCorner_Highlight_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_Highlight_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Bottom.
        /// </summary>
        public static string Theme_Sets_BottomCorner_IconBottom {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_IconBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Bottom Gradient Color.
        /// </summary>
        public static string Theme_Sets_BottomCorner_IconBottom_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_IconBottom_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Top.
        /// </summary>
        public static string Theme_Sets_BottomCorner_IconTop {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_IconTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Top Gradient Color.
        /// </summary>
        public static string Theme_Sets_BottomCorner_IconTop_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_IconTop_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_BottomCorner_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_BottomCorner_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomCorner_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string Theme_Sets_BottomInner_Border {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomInner_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Color.
        /// </summary>
        public static string Theme_Sets_BottomInner_Border_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomInner_Border_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        public static string Theme_Sets_BottomInner_Glow {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomInner_Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow Color.
        /// </summary>
        public static string Theme_Sets_BottomInner_Glow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomInner_Glow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Theme_Sets_BottomInner_Highlight {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomInner_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Color.
        /// </summary>
        public static string Theme_Sets_BottomInner_Highlight_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomInner_Highlight_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_BottomInner_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomInner_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_BottomInner_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomInner_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        public static string Theme_Sets_BottomOuter_Glow {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomOuter_Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Glow Color.
        /// </summary>
        public static string Theme_Sets_BottomOuter_Glow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomOuter_Glow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_BottomOuter_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomOuter_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_BottomOuter_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomOuter_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripes.
        /// </summary>
        public static string Theme_Sets_BottomOuter_Stripe {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomOuter_Stripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripes Behind the Open/Close Button Color.
        /// </summary>
        public static string Theme_Sets_BottomOuter_Stripe_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_BottomOuter_Stripe_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        public static string Theme_Sets_Cursor_Glow {
            get {
                return ResourceManager.GetString("Theme_Sets_Cursor_Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow Color.
        /// </summary>
        public static string Theme_Sets_Cursor_Glow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Cursor_Glow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_Cursor_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_Cursor_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_Cursor_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Cursor_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading.
        /// </summary>
        public static string Theme_Sets_Cursor_Shading {
            get {
                return ResourceManager.GetString("Theme_Sets_Cursor_Shading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading Color.
        /// </summary>
        public static string Theme_Sets_Cursor_Shading_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Cursor_Shading_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_Demo_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_Demo_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_Demo_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Demo_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string Theme_Sets_Demo_Text {
            get {
                return ResourceManager.GetString("Theme_Sets_Demo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string Theme_Sets_Demo_Text_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Demo_Text_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading.
        /// </summary>
        public static string Theme_Sets_File_Dark {
            get {
                return ResourceManager.GetString("Theme_Sets_File_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading Color.
        /// </summary>
        public static string Theme_Sets_File_Dark_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_File_Dark_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        public static string Theme_Sets_File_Light {
            get {
                return ResourceManager.GetString("Theme_Sets_File_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow Color.
        /// </summary>
        public static string Theme_Sets_File_Light_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_File_Light_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Theme_Sets_File_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_File_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Color.
        /// </summary>
        public static string Theme_Sets_File_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_File_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string Theme_Sets_File_Shadow {
            get {
                return ResourceManager.GetString("Theme_Sets_File_Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow under Icon.
        /// </summary>
        public static string Theme_Sets_File_Shadow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_File_Shadow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading.
        /// </summary>
        public static string Theme_Sets_Folder_Dark {
            get {
                return ResourceManager.GetString("Theme_Sets_Folder_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading Color.
        /// </summary>
        public static string Theme_Sets_Folder_Dark_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Folder_Dark_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Theme_Sets_Folder_Light {
            get {
                return ResourceManager.GetString("Theme_Sets_Folder_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Face Highlight.
        /// </summary>
        public static string Theme_Sets_Folder_Light_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Folder_Light_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Theme_Sets_Folder_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_Folder_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Color.
        /// </summary>
        public static string Theme_Sets_Folder_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Folder_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string Theme_Sets_Folder_Shadow {
            get {
                return ResourceManager.GetString("Theme_Sets_Folder_Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow under Folder.
        /// </summary>
        public static string Theme_Sets_Folder_Shadow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Folder_Shadow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Pressed.
        /// </summary>
        public static string Theme_Sets_FolderArrow_ArrowPressed {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_ArrowPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Pressed Color.
        /// </summary>
        public static string Theme_Sets_FolderArrow_ArrowPressed_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_ArrowPressed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Glow.
        /// </summary>
        public static string Theme_Sets_FolderArrow_ArrowShadow {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_ArrowShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Shadow/Glow Color.
        /// </summary>
        public static string Theme_Sets_FolderArrow_ArrowShadow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_ArrowShadow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Unpressed.
        /// </summary>
        public static string Theme_Sets_FolderArrow_ArrowUnpressed {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_ArrowUnpressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Unpressed Color.
        /// </summary>
        public static string Theme_Sets_FolderArrow_ArrowUnpressed_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_ArrowUnpressed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        public static string Theme_Sets_FolderArrow_Glow {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_Glow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow Color.
        /// </summary>
        public static string Theme_Sets_FolderArrow_Glow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_Glow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Theme_Sets_FolderArrow_Highlight {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Color.
        /// </summary>
        public static string Theme_Sets_FolderArrow_Highlight_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_Highlight_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_FolderArrow_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_FolderArrow_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading.
        /// </summary>
        public static string Theme_Sets_FolderArrow_Shading {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_Shading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading Color.
        /// </summary>
        public static string Theme_Sets_FolderArrow_Shading_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_FolderArrow_Shading_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Theme_Sets_Game_Light {
            get {
                return ResourceManager.GetString("Theme_Sets_Game_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Theme_Sets_Game_Light_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Game_Light_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_Game_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_Game_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_Game_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Game_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string Theme_Sets_Game_TextMain {
            get {
                return ResourceManager.GetString("Theme_Sets_Game_TextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string Theme_Sets_Game_TextMain_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Game_TextMain_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow.
        /// </summary>
        public static string Theme_Sets_OpenClose_Light {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow Color.
        /// </summary>
        public static string Theme_Sets_OpenClose_Light_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_Light_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Pressed.
        /// </summary>
        public static string Theme_Sets_OpenClose_Pressed {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Pressed Color.
        /// </summary>
        public static string Theme_Sets_OpenClose_Pressed_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_Pressed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Position.
        /// </summary>
        public static string Theme_Sets_OpenClose_ShadowPos {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_ShadowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Position (Vertical).
        /// </summary>
        public static string Theme_Sets_OpenClose_ShadowPos_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_ShadowPos_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Pressed.
        /// </summary>
        public static string Theme_Sets_OpenClose_TextPressed {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_TextPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Pressed Color.
        /// </summary>
        public static string Theme_Sets_OpenClose_TextPressed_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_TextPressed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Glow.
        /// </summary>
        public static string Theme_Sets_OpenClose_TextShadow {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_TextShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Glow Color.
        /// </summary>
        public static string Theme_Sets_OpenClose_TextShadow_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_TextShadow_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Unpressed.
        /// </summary>
        public static string Theme_Sets_OpenClose_TextUnpressed {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_TextUnpressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Unpressed Color.
        /// </summary>
        public static string Theme_Sets_OpenClose_TextUnpressed_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_TextUnpressed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Unpressed.
        /// </summary>
        public static string Theme_Sets_OpenClose_Unpressed {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_Unpressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Unpressed Color.
        /// </summary>
        public static string Theme_Sets_OpenClose_Unpressed_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_OpenClose_Unpressed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Opacity.
        /// </summary>
        public static string Theme_Sets_Top_AltOpacity {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_AltOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Texture Opacity.
        /// </summary>
        public static string Theme_Sets_Top_AltOpacity_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_AltOpacity_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Color.
        /// </summary>
        public static string Theme_Sets_Top_FadeToValue {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_FadeToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Fade Value.
        /// </summary>
        public static string Theme_Sets_Top_FadeToValue_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_FadeToValue_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient.
        /// </summary>
        public static string Theme_Sets_Top_Gradient {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade to Color Ratio.
        /// </summary>
        public static string Theme_Sets_Top_Gradient_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_Gradient_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_Top_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_Top_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Opacity.
        /// </summary>
        public static string Theme_Sets_Top_Opacity {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Texture Opacity.
        /// </summary>
        public static string Theme_Sets_Top_Opacity_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_Top_Opacity_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Theme_Sets_TopCorner_Main {
            get {
                return ResourceManager.GetString("Theme_Sets_TopCorner_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Theme_Sets_TopCorner_Main_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_TopCorner_Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string Theme_Sets_TopCorner_Text {
            get {
                return ResourceManager.GetString("Theme_Sets_TopCorner_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string Theme_Sets_TopCorner_Text_Desc {
            get {
                return ResourceManager.GetString("Theme_Sets_TopCorner_Text_Desc", resourceCulture);
            }
        }
    }
}
